"use strict";
window.MathText = (function () {
  var T = {
    appTitle: "לוח הכפל",
    staleCard: "המשחק נפתח בחלון אחר — רענני 🔄",
    saveFailure: "השמירה נכשלה — ננסה שוב",
    schemaTooNew: "הגרסה הזו ישנה מדי — צריך לעדכן את האפליקציה",

    home: {
      startCta: "בואי נתחיל!",
      resumeCta: "ממשיכות!",
      resumeFallingCta: "ממשיכות! 🎈",
      fallingBtn: "מספרים נופלים 🎈",
      greeting: function (name) { return "היי, " + name + "!"; },
      mapBtn: "המפה שלי 🗺️",
      mapStatus: function (table, progress, required) { return "🐢 את בתחנה " + tableTag(table) + " · " + bdi(progress + "/" + required); },
      mapDone: "🐢👑 הגעת לטירה! כל התחנות שלך",
      collectionBtn: "האוסף שלי 🎁",
      rewardsBtn: "פרסים 🎈",
      parentBtn: "הורים",
      installBanner: "כדי להתקין: לחצי על שיתוף ⬆️ ואז \"הוספה למסך הבית\"",
      backupBanner: "לא גיבינו לאחרונה — כדאי לבקש מההורים לגבות",
      streakLabel: function (n) { return "רצף של " + bdi(n) + " ימים 🔥"; },
    },

    parentSetup: {
      title: "בואו נגדיר",
      nameLabel: "מה השם של הילדה?",
      namePlaceholder: "השם",
      pinLabel: "בחרו קוד בן 4 ספרות",
      pinConfirmLabel: "הקלידו שוב את הקוד",
      continueBtn: "המשך",
      errorPinFormat: "הקוד חייב להיות 4 ספרות",
      errorPinMismatch: "הקודים לא תואמים",
      errorName: "צריך למלא שם",
      recoveryTitle: "קוד השחזור שלכם",
      recoveryHint: "כתבו את זה במקום בטוח — בלעדיו אי אפשר לשחזר קוד שכוח",
      recoveryCheckbox: "כתבתי אותו",
      finishBtn: "סיימנו, בואי נשחק!",
      restoreFound: function (n) { return "נמצאו נתונים קודמים במכשיר הזה (" + bdi(n) + " סבבים) — לשחזר אותם?"; },
      restoreFailed: function (err) { return "השחזור נכשל: " + err; },
      restoreBtn: "כן, לשחזר",
      restoreThenSetup: "ההתקדמות שוחזרה — עכשיו בחרו שם וקוד הורים חדש",
      cloudRestoreTitle: "יש לכם גיבוי בענן? הדביקו את ה-Token ושחזרו",
      cloudRestoreBtn: "שחזור מהענן",
    },

    question: {
      equalsCoin: function (n) { return "שווה " + bdi(n) + " 🪙"; },
      check: "✓",
      clear: "⌫",
      showKeyboard: "הציגי מקלדת",
      showNumpad: "הציגי מקלדת מספרים",
      beatClock: "מהר מאוד! ⚡ מטבעות כפולים!",
      exitConfirmTitle: "יוצאות? נמשיך אחר כך מאותו מקום",
      exitConfirmYes: "כן, יוצאות",
      exitConfirmNo: "לא, ממשיכות",
      timeoutMessage: "הצב הגיע ונח 😴 — אפשר לאט 🙂",
      helperCaption: function (a, b, product) { return a + " × " + b + " = " + product; },
      helperRows: function (a, b) { return a === 1 ? "שורה אחת של " + bdi(b) : bdi(a) + " שורות של " + bdi(b); },
      strategyIntro: "דרך קלה לזכור:",
      // S3-2: the per-trick Hebrew phrasing moved verbatim from app.js's
      // strategyHint(a, b) switch — app.js still picks the operand (n) and
      // its partner (m) and computes the product (p); these templates only
      // build the display string, exactly as the switch cases did.
      strategies: {
        10: function (m, p) { return '<span class="ltr">' + m + " × 10 = " + m + "0</span>" + " — מוסיפים 0"; },
        9: function (m, p) { return '<span class="ltr">' + "10 × " + m + " − " + m + " = " + (10 * m) + " − " + m + " = " + p + "</span>"; },
        5: function (m, p) { return '<span class="ltr">' + "10 × " + m + " = " + (10 * m) + "</span>" + ", חצי מזה: " + '<span class="ltr">' + p + "</span>"; },
        2: function (m, p) { return '<span class="ltr">' + m + " + " + m + " = " + p + "</span>"; },
        4: function (m, p) { return '<span class="ltr">' + "2 × " + m + " = " + (2 * m) + "</span>" + ", כפול 2: " + '<span class="ltr">' + p + "</span>"; },
        8: function (m, p) { return '<span class="ltr">' + "4 × " + m + " = " + (4 * m) + "</span>" + ", כפול 2: " + '<span class="ltr">' + p + "</span>"; },
        3: function (m, p) { return '<span class="ltr">' + "2 × " + m + " + " + m + " = " + (2 * m) + " + " + m + " = " + p + "</span>"; },
        6: function (m, p) { return '<span class="ltr">' + "5 × " + m + " + " + m + " = " + (5 * m) + " + " + m + " = " + p + "</span>"; },
        7: function (m, p) { return '<span class="ltr">' + "5 × " + m + " + 2 × " + m + " = " + (5 * m) + " + " + (2 * m) + " = " + p + "</span>"; },
        default: function (m, p) { return '<span class="ltr">' + m + " × 1 = " + m + "</span>" + " — כפול 1 נשאר אותו מספר"; },
      },
      commutative: function (a, b, p) { return "וגם " + '<span class="ltr">' + b + " × " + a + " = " + p + "</span>"; },
      interruptedLabel: "ממשיכות בלי שעון",
      wrongAnswerWas: function (n) { return "התשובה היא " + n; },
      retryNowYouKnow: "עכשיו את יודעת! ✨",
      fallingLandedLabel: "נחתו! אפשר לבחור בנחת 🙂",
      // V2-DESIGN §8 (mirror pairs): shown under the equation exactly when
      // this question is the second of a mirror pair (current.mirror).
      mirrorHint: "ועכשיו הפוך! אותה תשובה 😉",
      exitButton: "✕",
      exitBottom: "יציאה — ההתקדמות נשמרת",
      continueBtn: "הבנתי, ממשיכות ✓",
    },

    summary: {
      perfectTitle: "מושלם!!! 🎆",
      perfectSub: "כל התשובות נכונות!",
      nearPerfectTitle: "כמעט מושלם! 🌟",
      encouragingTitle: "כל הכבוד, ממשיכות!",
      learnedToday: "למדנו היום",
      learnedItem: function (a, b, product) { return a + " × " + b + " = " + product; },
      unlockReveal: "פתחת מדבקה חדשה!",
      stationReached: function (table) { return "הגעת לתחנה " + tableTag(table) + "! 🎉"; },
      stationsReached: function (tables) { return "הגעת ל-" + bdi(tables.length) + " תחנות: " + tables.map(tableTag).join(" ") + " 🎉"; },
      nextSessionBtn: "עוד סבב!",
      doneBtn: "סיימנו",
      coinsEarned: function (n) { return bdi("+" + n) + " 🪙"; },
      perfectSeriesTitle: function (n) { return bdi(n) + " בסדרה!!! 🎆🎆"; },
      perfectSeriesSub: "שני סבבים מושלמים ברצף! מדהים!",
      perfectSeriesSub3: "שלושה סבבים מושלמים ברצף (או יותר)! אלופה!!!",
      seriesBonus: function (n) { return "בונוס סדרה " + bdi("+" + n) + " 🪙"; },
    },

    map: {
      title: "המפה שלי",
      backBtn: "חזרה",
      castle: "🏰",
      stationTitle: function (table) { return "תחנה " + tableTag(table); },
      reachedLabel: "הגעת! ⭐",
      currentLabel: "כאן את עכשיו 🐢",
      aheadLabel: "עוד לא",
      tapHint: "לחצי על תחנה כדי לראות את התרגילים שלה",
      chipsLegend: "ירוק = יודעת מצוין · כתום = בלמידה · אפור = עוד לא ניסית",
      doneAll: "כל התחנות הושלמו! 👑",
      goldsSticker: function (name) { return "מזהיבה את " + name; },
    },

    // V2-DESIGN §3.1/§3.4: name + nick for every one of the 48 stickers
    // (both albums), verbatim from the design doc — extracted programmatically
    // from docs/V2-DESIGN.md lines 53/63 to avoid any transcription error.
    stickers: {
      cat: { name: "חתול", nick: "מיצי הפוזזת" },
      dog: { name: "כלב", nick: "בובי הנאמן" },
      fox: { name: "שועל", nick: "שוקו הערמומי" },
      owl: { name: "ינשוף", nick: "חכמוני" },
      bee: { name: "דבורה", nick: "זמזומית" },
      frog: { name: "צפרדע", nick: "קפצוני" },
      fish: { name: "דג", nick: "בועית" },
      duck: { name: "ברווז", nick: "קוואקי" },
      panda: { name: "פנדה", nick: "פנדי הישנונית" },
      koala: { name: "קואלה", nick: "קוקו המחבק" },
      lion: { name: "אריה", nick: "שאגי המלך" },
      tiger: { name: "נמר", nick: "פסי" },
      zebra: { name: "זברה", nick: "פסיפס" },
      giraffe: { name: "ג'ירפה", nick: "צווארונת" },
      elephant: { name: "פיל", nick: "פילי החדק" },
      monkey: { name: "קוף", nick: "קפצני השובב" },
      rabbit: { name: "ארנב", nick: "גזרי" },
      hedgehog: { name: "קיפוד", nick: "דוקרני החמוד" },
      turtle: { name: "צב", nick: "לאטי" },
      dolphin: { name: "דולפין", nick: "צלילי" },
      butterfly: { name: "פרפר", nick: "פרפרית הצבעונית" },
      ladybug: { name: "פרת משה רבנו", nick: "נקודונת" },
      unicorn: { name: "חד-קרן", nick: "קשתי" },
      dragon: { name: "דרקון", nick: "להבי הידידותי" },
      rocket: { name: "חללית", nick: "זיקי" },
      ufo: { name: "צלחת מעופפת", nick: "בלופי" },
      planet: { name: "כוכב לכת", nick: "טבעתי" },
      moon: { name: "ירח", nick: "לונה" },
      star: { name: "כוכב", nick: "נצנצת" },
      rainbow: { name: "קשת", nick: "צבעונית" },
      castle: { name: "טירה", nick: "מגדלית" },
      ferris: { name: "גלגל ענק", nick: "סיבובי" },
      carousel: { name: "קרוסלה", nick: "סוסוני" },
      circus: { name: "קרקס", nick: "ליצנית" },
      train: { name: "רכבת", nick: "טו-טו" },
      helicopter: { name: "מסוק", nick: "פרפרון" },
      sailboat: { name: "סירת מפרש", nick: "רוחית" },
      racecar: { name: "מכונית מרוץ", nick: "זומי" },
      tractor: { name: "טרקטור", nick: "חורשי" },
      canoe: { name: "קאנו", nick: "שייטי" },
      volcano: { name: "הר געש", nick: "לוהט" },
      island: { name: "אי", nick: "חופית" },
      tent: { name: "אוהל", nick: "מחנאית" },
      balloon: { name: "בלון", nick: "פוחי" },
      kite: { name: "עפיפון", nick: "רוחיתה" },
      compass: { name: "מצפן", nick: "כיווני" },
      map: { name: "מפה", nick: "דרכי" },
      crown: { name: "כתר", nick: "מלכותית" },
    },

    // V2-DESIGN §3.1/§3.4: T.albums[id] = title, user-visible (designer-supplied 2026-08-29).
    albums: {
      animals: "חיות",
      adventure: "הרפתקאות",
    },

    collection: {
      title: "האוסף שלי",
      backBtn: "חזרה",
      nextUnlockProgress: function (remaining) { return "עוד " + bdi(remaining) + " מטבעות למדבקה הבאה"; },
      allUnlocked: "אספת את כל המדבקות! 🏆",
      albumDone: "🏆 האלבום הושלם!",
    },

    rewards: {
      title: "פרסים",
      backBtn: "חזרה",
      requestBtn: "לבקש",
      pendingLabel: "מחכה לאישור ⏳",
      noRewards: "עוד אין פרסים — בקשו מההורים להוסיף",
    },

    parent: {
      title: "הורים",
      pinPrompt: "קוד הורים",
      pinPlaceholder: "הקלידו קוד",
      unlockBtn: "כניסה",
      wrongPin: "קוד שגוי",
      forgotPin: "שכחתי קוד",
      recoveryPrompt: "הקלידו את קוד השחזור",
      recoverySubmit: "אשרו",
      wrongRecovery: "קוד שחזור שגוי",
      newPinPrompt: "בחרו קוד חדש בן 4 ספרות",
      newPinConfirmPrompt: "הקלידו שוב את הקוד החדש",
      setNewPinBtn: "שמרו קוד חדש",
      backToPin: "חזרה",

      settingsTitle: "הגדרות",
      nameLabel: "שם הילדה",
      challengeLabel: "מצב אתגר",
      timeLimitLabel: "זמן לשאלה (שניות)",
      soundLabel: "צלילים",
      fallingEnableLabel: "מספרים נופלים 🎈 — מצב נוסף",
      fallingDurationLabel: "זמן נפילה (שניות)",
      fallingOptionsLabel: "מספר בועות לבחירה",
      sessionSizeLabel: "מספר תרגילים בסבב",
      changePinBtn: "שינוי קוד",
      saveSettingsBtn: "שמירה",
      settingsSaved: "נשמר ✓",

      storageStatusTitle: "מצב אחסון",
      persistedYes: "persisted: כן",
      persistedNo: "persisted: לא",
      persistedUnknown: "persisted: לא זמין",
      standaloneYes: "standalone: כן",
      standaloneNo: "standalone: לא",

      rewardsTitle: "ניהול פרסים",
      addRewardBtn: "הוספת פרס",
      rewardNamePlaceholder: "שם הפרס",
      rewardCostPlaceholder: "מחיר במטבעות",
      deactivateBtn: "הסרה",
      pendingRequestsTitle: "בקשות ממתינות",
      approveBtn: "אישור",
      rejectBtn: "דחייה",
      noPendingRequests: "אין בקשות ממתינות",
      insufficientBalanceMsg: "אין מספיק מטבעות לאישור הבקשה",

      statsTitle: "התקדמות",
      kpiSessions: "סבבים",
      kpiCoins: "מטבעות (סה\"כ)",
      kpiMastered: "נלמדו לגמרי",
      kpiStreak: "רצף ימים",
      kpiMap: "תחנות במפה",
      kpiAccuracy: "דיוק כללי",
      trendAccuracy: "דיוק (30 סבבים אחרונים)",
      trendSpeed: "זמן ממוצע (מ\"ש)",
      trendMastered: "נלמדו לגמרי",
      trendCoins: "מטבעות לסבב",
      heatmapTitle: "מפת חום — כל העובדות",
      heatmapLegend: "ירוק = נלמד לגמרי · צהוב = בלמידה (70%+) · כתום = בלמידה (מתחת ל-70%) · אפור = עוד לא ניסתה",
      modeNames: { typed: "מקלדת ⌨️", falling: "בלונים 🎈", tetris: "מלבנים 🧱" },
      modeLegend: "קו לכל מצב משחק",
      weakestTitle: "8 העובדות הכי קשות",
      historyTitle: "היסטוריית סבבים",
      historyOpen: "פתוח",

      dataTitle: "גיבוי ושחזור",
      exportBtn: "ייצוא גיבוי",
      importBtn: "ייבוא מקובץ",
      importPreviewTitle: "תצוגה מקדימה",
      importWarningActive: "הסבב הפתוח יימחק",
      importConfirmBtn: "אישור ייבוא",
      importCancelBtn: "ביטול",
      importPinPrompt: "הקלידו קוד לאישור",
      undoBtn: "ביטול הפעולה האחרונה",
      evidenceRebuiltLabel: "עדכון נתוני למידה",
      evidenceRebuildStates: { rebuilt: "בוצע", pending: "ממתין", trimmed: "לא נדרש", malformed: "לא בוצע — נתונים לא עקביים" },
      restoreLocalBtn: function (n) { return "שחזור מהעותק המקומי (" + bdi(n) + " סבבים)"; },
      restoredMsg: "שוחזר בהצלחה",
      restoreFailed: function (err) { return "השחזור נכשל: " + err; },
      exportShareHint: "בחלון שנפתח בחרו \"שמירה בקבצים\" (Save to Files) ושמרו ב-iCloud Drive",
      exportDone: "הגיבוי נשמר ✓",
      exportCancelled: "הגיבוי בוטל",
      cloudTitle: "גיבוי אוטומטי לענן ☁️",
      cloudHint: "אחרי כל סבב הנתונים נשמרים ב-Gist פרטי בחשבון GitHub שלכם. צריך Token עם הרשאת gist בלבד (README מסביר).",
      cloudTokenPlaceholder: "הדביקו כאן את ה-Token",
      cloudSaveBtn: "שמירה ובדיקה",
      cloudBackupNowBtn: "גיבוי עכשיו",
      cloudRestoreBtn: "שחזור מהענן",
      cloudDisconnectBtn: "ניתוק",
      cloudConnected: "מחובר ✓",
      cloudNotConnected: "לא מחובר",
      cloudLastOk: function (d) { return "גיבוי אחרון לענן: " + bdi(d) + " ✓"; },
      cloudLastError: function (e) { return "הגיבוי האחרון נכשל: " + e; },
      cloudChecking: "בודקים…",
      cloudTokenBad: function (e) { return "ה-Token לא עובד: " + e; },
      cloudBackupDone: "נשמר בענן ✓",
      cloudRestorePreview: function (d, n) { return "נמצא גיבוי בענן מ-" + bdi(d) + " (" + bdi(n) + " סבבים)"; },
      cloudFoundExisting: "נמצא בחשבון גיבוי גדול יותר מהמכשיר — הוא לא יידרס: הגיבויים החדשים יישמרו בנפרד עד שתלחצו \"שחזור מהענן\".",
      cloudRestoreConfirmBtn: "אישור שחזור",
      cloudRestoreWarnSmaller: "שימו לב: בענן פחות סבבים מאשר במכשיר",
      cloudEmptySkipped: "אין עדיין סבבים — הגיבוי יתחיל אחרי הסבב הראשון",
      cloudSecretNote: "ה-Gist \"סודי\": מי שמחזיק בקישור יכול לקרוא אותו; אין בו קוד הורים.",
      undoneMsg: "בוטל בהצלחה",
      resetBtn: "איפוס כל הנתונים",
      resetConfirmPrompt: "כדי לאפס, הקלידו \"מחק\" והכניסו קוד (הקוד וה-Token לענן נשמרים; הגיבוי בענן יתחיל מחדש)",
      resetTypeConfirm: "מחק",
      resetTypeLabel: "הקלידו \"מחק\"",
      resetTypeMismatch: "צריך להקליד בדיוק \"מחק\"",
      resetPinLabel: "קוד",
      resetConfirmBtn: "איפוס סופי",
      resetCancelBtn: "ביטול",
      lastExportLabel: function (dateStr) { return "גיבוי אחרון: " + dateStr; },
      neverExported: "לא גובה מעולם",
      removedSuffix: " (הוסר)",
      noDataYet: "אין עדיין נתונים",
      noSessionsYet: "אין עדיין סבבים",
      invalidFile: "קובץ לא תקין",
      genericError: "שגיאה",
      sessionLabel: function (i) { return "סבב " + i; },
      importSummary: function (sessions, coins, date) { return bdi(sessions) + " סבבים, " + bdi(coins) + " מטבעות, ייצוא מ-" + bdi(date); },
      masteryNames: { new: "חדש", learning: "בלמידה", mastered: "נלמד לגמרי" },
      // V2-DESIGN §8: heat-map tooltip gains this after the mastery name for
      // non-square facts (mirrorSuffix null for squares, where mirror
      // doesn't apply — see Stats.heatmap's mirrorOk).
      mirrorState: { ok: "שני הכיוונים ✓ (מהר)", partial: "שני הכיוונים ✓", no: "כיוון אחד בלבד" },
      heatmapTooltip: function (a, b, masteryName, mirrorSuffix) {
        return masteryName + (mirrorSuffix ? " (" + mirrorSuffix + ")" : "") + ": " + a + "\u00d7" + b;
      },
    },

    misc: {
      updateAvailable: "יש גרסה חדשה — רענני",
      reloadBtn: "רענני",
    },
  };

  function escapeHtml(str) {
    return String(str == null ? "" : str).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }

  // Isolates a number (optionally with a sign/prefix like "+21") from the
  // surrounding RTL bidi context (I10) — without this, "+21" can visually
  // reorder to "21+" inside RTL text (confirmed live: the summary screen's
  // coin badge). Wrap every interpolated number, not just equations.
  // "×7" has no strong-direction character, so inside RTL text it flips to
  // "7×"; an explicit LTR island keeps the × in front (I10).
  function tableTag(n) { return '<span class="ltr">×' + Number(n) + "</span>"; }

  function bdi(content) {
    return "<bdi>" + content + "</bdi>";
  }

  return { T: T, escapeHtml: escapeHtml, tableTag: tableTag, bdi: bdi };
})();
