// Service worker: cache-first for same-origin, network passthrough for
// fonts/cross-origin. APP_VERSION/RELEASE/HASHED_ASSETS are generated by
// `node tools/bump-version.js <x.y.z>` (CLAUDE.md rule 7) — never hand-edit
// these three lines; run the tool before every commit that touches a
// deployable file, or tests/deploy-contract.test.js fails the suite.
"use strict";

var APP_VERSION = "0.15.0";
var RELEASE = "0.15.0-cd9bca3785";
var HASHED_ASSETS = ["core.js?v=5186c3ee07", "strings.js?v=19c1797be4", "app.js?v=31073d78b1", "styles.css?v=2663579693"];
var CACHE_NAME = "mathtrainer-" + RELEASE;
// index.html/manifest/icons are precached unversioned but still busted on
// every deploy because RELEASE (part of CACHE_NAME) folds in their bytes via
// the fingerprint the bump tool computes — see docs/V2-DESIGN.md §7.1.
var PRECACHE_URLS = ["./", "index.html"].concat(HASHED_ASSETS, ["manifest.webmanifest", "icon-180.png", "icon-512.png"]);

self.addEventListener("install", function (event) {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      // cache: "reload" bypasses the HTTP cache so a new RELEASE never
      // precaches a stale asset next to a fresh index.html (version skew
      // seen live on 2026-08-27: old core.js + new index.html froze feedback).
      .then(function (cache) {
        // Self-consistency gate (review 2026-08-28, S1 MEDIUM-2 + fix-verify):
        // a CDN can hand us a fresh sw.js next to an edge-stale entry page;
        // precaching that pair would seal the exact skew this contract exists
        // to prevent. Read BOTH entry URLs fresh, refuse to install unless each
        // references every hashed asset this release expects, and cache the
        // very Response that was checked. A failed install keeps the old
        // SW/cache and the browser retries on the next update check.
        var ENTRY_URLS = ["./", "index.html"]; // both are edge-cached separately; the PWA launches from "./"
        return Promise.all(ENTRY_URLS.map(function (entry) {
          return fetch(new Request(entry, { cache: "reload" })).then(function (res) {
            if (!res.ok) throw new Error(entry + " " + res.status);
            return res.clone().text().then(function (indexText) {
              var missing = HASHED_ASSETS.filter(function (url) { return indexText.indexOf(url) === -1; });
              if (missing.length) throw new Error(entry + " does not reference " + missing.join(", ") + " — edge skew, retry later");
              return { entry: entry, res: res };
            });
          });
        })).then(function (checked) {
          // Only after BOTH entries validated: cache exactly the bytes that were
          // checked (no second read), so a failed gate leaves no partial cache.
          return Promise.all(checked.map(function (c) { return cache.put(c.entry, c.res); }));
        }).then(function () {
          return cache.addAll(PRECACHE_URLS.filter(function (u) { return ENTRY_URLS.indexOf(u) === -1; })
            .map(function (url) { return new Request(url, { cache: "reload" }); }));
        });
      })
      .then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener("activate", function (event) {
  event.waitUntil(
    caches
      .keys()
      .then(function (names) {
        return Promise.all(
          names.filter(function (name) { return name !== CACHE_NAME; }).map(function (name) { return caches.delete(name); })
        );
      })
      .then(function () { return self.clients.claim(); })
      .then(function () { return notifyClients(); })
  );
});

function notifyClients() {
  return self.clients.matchAll().then(function (clients) {
    clients.forEach(function (client) {
      client.postMessage({ type: "updated", version: APP_VERSION });
    });
  });
}

self.addEventListener("fetch", function (event) {
  var url = new URL(event.request.url);
  if (url.origin !== self.location.origin) {
    return; // network passthrough (fonts, etc.) — not intercepted, not cached
  }
  event.respondWith(
    caches.match(event.request).then(function (cached) {
      return cached || fetch(event.request);
    })
  );
});
